{{- if .Values.eso.enabled }}
{{$eso:= .Values.eso.ClusterSecretStore}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{.Values.eso.name}}-secretstore
spec:
  provider:
    vault:
      server: {{$eso.vault.server}}
      path: {{$eso.vault.path}}
      version: {{$eso.vault.version}}
      auth:
        tokenSecretRef:
          name: {{$eso.auth.tokenSecretRef.name}}
          key: {{$eso.auth.tokenSecretRef.key}}
          namespace: {{$eso.auth.tokenSecretRef.namespace}}
{{end}}
