{{- if .Values.eso.enabled }}
{{ $eso:= .Values.eso}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{$eso.name}}
  namespace: {{$eso.externalSecret.namespace}}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{$eso.name}}-secretstore
    kind: ClusterSecretStore
  target:
    name: {{$eso.externalSecret.target_secret}}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{$eso.externalSecret.vault_secret_name}}
{{end}}