"""empty message

Revision ID: 0488f58e8b4d
Revises: 10f430fa8718
Create Date: 2025-09-19 12:52:27.969192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0488f58e8b4d'
down_revision = '10f430fa8718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('email2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email2', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
