{{ range $alerts := .Values.alertsconfig.alertmanagerConfig.receivers}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    release: {{ $.Release.Name }}
  name: {{.name}}-config
spec:
  receivers:
    - name: {{.name}}
      slackConfigs:
      {{ .slackConfigs | toYaml| nindent 6 }}
  route:
    receiver: {{$.Values.alertsconfig.alertmanagerConfig.route.receiver}}
---
{{end}}