apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argo-ns
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/one2nc/harshwardhan-sre-bootcamp.git
  username: <USERNAME>
  password: <PASSWORD>
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-api
  namespace: argo-ns
spec:
  project: default
  source:
    repoURL: https://github.com/one2nc/harshwardhan-sre-bootcamp.git
    targetRevision: helm
    path: k8s/Helm/student-api-chart
  destination:
    name: in-cluster
    namespace: student-api
  syncPolicy:
    automated:
        prune: true
        selfHeal: true